### ISSUE TITLE
My printer isn't working

### ISSUE THREAD

**Issue by wizzwizz4** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#393]
I used to be able to use my printer, but after coming back from holiday it doesn't work. Every time I try to print, a box comes up and even after I close it it still doesn't work.

**Comment by wizzwizz4** [comment]
The techs came, muttering something about 10T and peb cake. My printer prints now, but the colours are all wrong.

**Comment by anderejd** [comment]
Have you connected the power cable __both__ to the printer __and__ to the wall?

**Comment by wizzwizz4** [comment]
@emiln There are two cables coming out of the printer. One is a grey Cat5e cable (according to the tiny tiny tiny lettering on it) and that's plugged into nothing. The other one's the power cable and that's definitely plugged in because the printer is on.

The printer prints fine. It's just the colours that are wrong when I print. Perhaps if I give the printer some of @lifenautjoe's cake it'll print properly again.

**Comment by morganbye** [comment]
I'm afraid that to get to the root of the problem, we're going to have to ask you to perform some further tests.

What happens if you print on different colored paper?

**Comment by wizzwizz4** [comment]
@morganbye The colours go really really wrong. I can't even see some of them any more.

Can I have some opposite colour paper so the colours will go right again? I don't know where to get that.

**Comment by claui** [comment]
Hey folks, I got some holiday pictures by email but when I try to print them out the printer only prints question marks. Please advise

**Comment by lifenautjoe** [comment]
Dear Claudia,

Are the question marks like this ? Or this ¿ . Juan has been messing with
the language settings since the last week trying to print some of his
daughters homework.

Merry Christmas,
Joel.

**Comment by claui** [comment]
> Are the question marks like this ? Or this ¿

Yes, exactly!!

**Comment by wizzwizz4** [comment]
@cameronxm Your question marks need to be like ? and not like )EŁeł&ŁŁ® and they should be in a little box. Otherwise the printer won't work.

**Comment by Liu-Kai-1991** [comment]
Dear wizzwizz4,

Did you turn on the [switch](https://www.google.com/search?tbm=isch&q=switch&chips=q:switches,g_1:light:26yRTE1qEIw%3D&usg=AI4_-kTxAXspuiuwkVV3tPHj5jQ6DL6tyA&sa=X&ved=0ahUKEwiw6dX93qzfAhXpTN8KHT8ADZUQ4lYILSgA&biw=1707&bih=871&dpr=1.5) that controls the [outlet](https://www.google.com/search?biw=1707&bih=871&tbm=isch&sa=1&ei=J6saXPz-MeSkggefrJSQCQ&q=outlet+socket&oq=outlet+socket&gs_l=img.3...0.0..4769...0.0..0.0.0.......1......gws-wiz-img.I0GEANU0aHI) on the wall? (The outlet that connected to your printer through your power cable)

Thanks,
Kai

**Comment by lifenautjoe** [comment]
Speaking about cake, my son just scored an A+ on maths and I’ve brought
some cake downstairs to celebrate.

Feel free to come get some and happy holidays !

( Except you Trevor ! )

**Comment by wizzwizz4** [comment]
@lifenautjoe Thanks! I'm going to feed some more to my printer as an incentive to work again.

**Comment by stestagg** [comment]
Hi @wizzwizz4

What has happened is that the inks dried out during your holiday. The initial technician re-activated the printer but didn’t manage to hydrate the inks again.

As the support staff are currently all nursing hangovers, you’ll have to perform the steps yourself to fix the printer colours.

1.  Find the power cable for the printer
2. Unplug the  power cable at the printer end
3. Dip the end of the cable in a large glass of water
4.  Remove cable end from water and immediately re plug into the printer
5. The printer wills start the re-hydration process immediately. (There may be some smoke produced as the inks liquify again)

P.s.  we’re doing some power tests over the next few days, if the lights go off during this process, please wait for them to come back on before re-trying

**Comment by lifenautjoe** [comment]
Instructions still unclear @stestagg . Could you write a draft for a manual and schedule a meeting for review with the entire department? 

Cheers.


- Sent from my iPhone in the Caribbean

**Comment by claui** [comment]
@lifenautjoe The printer manual review meeting has been adjourned indefinitely because we couldn’t agree on whether it’s “liquefy” or “liquify.”

**Comment by stestagg** [comment]
@claui come on, this is getting ridiculous! 

The corporate spelling SOP *clearly* states on on page 803 that it's liquify, unless an approved exemption form from the compliant spelling board has been filed at least 5 working days before the incident.

I'm going to have to report this to compliance as you obviously have some training refresher courses to attend!

**Comment by claui** [comment]
@stestagg Thanks for the pointer! We actually tried to consult the SOP at some point during the meeting but the printer wouldn’t print it.

**Comment by wizzwizz4** [comment]
@claui I talked to the techs and apparently salt water works better for liquidation of the printer ink. But I've found somebody online called "Michael Marcovici" who says he can liquidate any assets, and printer ink is an asset, so I'm going to talk to him instead. I don't think **@lab** would like it if I put salt in their "specially cleaned" water; they didn't even like me dipping the plug in it!

**Comment by marcorm** [comment]
+1

**Comment by wizzwizz4** [comment]
My printer still doesn't work. Also, I was charged $500 by "Michael Marcovici, Attorney at Law" for not fixing the printer. How do you claim back money for company stuff again? I can't remember the form number.

**Comment by claui** [comment]
> How do you claim back money for company stuff again? I can't remember the form number.

We only accept submissions in printed form.

**Comment by wizzwizz4** [comment]
Yes, but what's the form number?

**Comment by claui** [comment]
> Yes, but what's the form number?

Look, my department is in the middle of reorganizing all forms. I’ll get back to you on that ASAP once the Numberwang committee has settled on the new number pooling scheme.

**Comment by marcorm** [comment]
> Hi and thank you for your message. I’m out of the office right now but I will get back to you as soon as possible. If you need something about the annual report, call Dorothy. For sales inquiries, please contact Michael on the 5th floor. If you’re Timmy and can’t find the remote again: it’s probably under the pillow. Don’t forget to floss before bedtime.
> 
> Regards,
> 
> Claudia
> Senior Group Manager of Enterprise Marketing

+2 

How do you know Timmy, it's my turtle!

**Comment by stestagg** [comment]
Please take me off this distribution list

**Comment by wizzwizz4** [comment]
@stestagg  You can press the thingy button to get off the list. I asked about this before, and apparently the list distributor can't get you off the list without you pressing the button thing.

**Comment by dribro** [comment]
Hi, I'm also having a printer issue.

**Comment by lifenautjoe** [comment]
> Hi, I'm also having a printer issue.

Hi @dribro , could you please share the color of the printer?

**Comment by wizzwizz4** [comment]
@lifenautjoe Hi my printer still isn't working can you fix it pleaase

**Comment by wizzwizz4** [comment]
I turned it off and n angain a lot of times and it dnsd't work. Look.=

**Comment by lifenautjoe** [comment]
Hi @wizzwizz4 , thanks for the buzz of notifications. It keep the pressure-driven culture alive. 

What's the color of your printer again?

**Comment by wizzwizz4** [comment]
My printer isn't printing colours right. They come out wrong.

**Comment by wizzwizz4** [comment]
@lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe @lifenautjoe

**Comment by wizzwizz4** [comment]
Answer me this is urgent why haven't you answered I've been waiting for half an hour.

**Comment by claui** [comment]
A case has been assigned in the service incident tracker. A contractor will be on-site soon and (hopefully) have a look at the printer.

This costs $2000 so I hope they’re going to figure it out!

**Comment by lifenautjoe** [comment]
Glad to read so @claui and looking forward to the report of the outcome.

Shall we schedule a meeting for next month to discuss findings @all ?




Regards,

Joel
Senior Executive Branch Group Manager of Business to Business Relationship Research & Analysis

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

Our company accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

WARNING: Computer viruses can be transmitted via email. The recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission.

**Comment by wizzwizz4** [comment]
@claui I found the printer in portrait mode when I came back. It looks like the contractor also sorted that wireless issue I've been complaining about. There are some sharp bits of metal sticking out of the back, though; maybe that's a safety hazard.

Also, it still won't print colours right.

**Comment by Aericio** [comment]
you can always try to rename the colors on the printer.

**Comment by Aericio** [comment]
![image](https://user-images.githubusercontent.com/16523741/54012929-9ae2fb80-411b-11e9-942f-6b923aaeb9a9.png)
it worked fine for me 👍

**Comment by stestagg** [comment]
Guys! (and Woman colleagues! I remember my mandatory sensitivity trainings..)

Ian from services just sent through the service report. It might be time to push for an IT refresh again, maybe it'll be successful this time.  I hear the lead-time for new equiement is down to 13 months now, so we  might get lucky
![csr100904532132-a-rept4-scan](https://user-images.githubusercontent.com/704526/54030290-0b812b00-41a3-11e9-8902-e01fc74e124e.jpg)

**Comment by wizzwizz4** [comment]
I plugged the internet calbele into the printer  and now it's print glbkac. Lot and lots of black.

**Comment by wizzwizz4** [comment]
ADlo my keybarod isn't workng. Whn I type leters it takes them more than 0 second sptt apper on the scren.

**Comment by wizzwizz4** [comment]
I rtyied to make it type faster by it didnt' work. The letters appear agter tn seocnas and out of order.

**Comment by wizzwizz4** [comment]
19 (tne s)ecnos

**Comment by wizzwizz4** [comment]
I fed my pirnter some more scake but now it won't print atk aol!!

**Comment by wizzwizz4** [comment]
IT@S BEEN OVER A WEEK AND I STILL HAVEN@T GOT ANY FIX TO MY PRINTER> I@VE BEEN WAITING ( DAYS> THIS IS GETTING RIDICULOUS NOW>

ALSO< MY KEYBOARD SEEMS TO WORK PROPERLY IF I HOLD DOWN SHIFT> I DON@T KNOW WHY> THANKS>

**Comment by ecurtin** [comment]
@wizzwizz4 I WAS ABLE TO PRINT THE OTHER DAY! ARE YOU STILL HAVING ISSUES? 

(ALSO I DIDN'T KNOW I COULD SHIFT MY KEYBOARD INTO A HIGHER PERFORMANCE MODE, THANKS FOR THE TECH TIP!!)

**Comment by PORTB** [comment]
Any update on this issue? I am experiencing a similar issue

**Comment by claui** [comment]
<sub>Claudia is out of office and may not respond.</sub>
___

**Comment by ryanolee** [comment]
Hi @wizzwizz4 ,
I was looking very carefully through the backlog of issues and it seems like it could be down to:
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/531
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/530
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/529
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/528
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/527
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/526
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/525
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/524
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/523
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/522
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/521
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/520
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/519
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/517
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/516
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/514
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/512
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/511
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/509
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/508
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/507
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/506
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/505
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/504
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/503
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/502
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/501
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/499
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/498
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/496
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/493
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/492
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/491
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/490
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/488
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/487
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/483
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/482
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/481
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/480
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/479
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/477
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/476
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/475
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/472
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/471
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/470
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/468
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/467
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/466
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/465
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/464
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/463
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/462
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/459
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/458
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/456
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/455
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/450
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/449
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/448
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/446
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/444
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/443
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/442
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/441
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/440
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/434
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/433
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/432
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/431
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/430
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/429
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/428
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/427
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/425
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/424
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/422
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/421
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/420
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/418
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/416
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/415
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/414
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/413
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/412
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/411
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/410
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/407
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/406
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/404
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/403
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/402
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/401
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/400
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/399
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/398
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/395
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/392
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/391
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/390
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/389
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/388
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/387
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/386
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/385
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/384
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/383
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/382
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/381
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/380
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/379
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/378
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/377
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/376
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/375
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/374
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/373
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/372
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/371
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/370
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/369
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/368
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/367
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/366
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/365
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/363
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/362
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/361
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/360
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/359
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/358
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/357
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/356
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/355
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/354
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/353
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/352
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/351
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/350
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/349
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/347
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/345
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/344
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/343
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/342
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/341
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/340
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/339
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/338
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/337
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/336
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/335
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/333
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/331
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/330
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/329
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/328
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/327
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/325
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/324
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/323
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/322
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/321
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/319
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/317
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/315
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/314
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/312
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/311
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/310
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/309
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/306
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/305
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/304
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/303
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/302
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/300
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/299
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/298
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/297
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/296
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/295
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/294
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/293
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/292
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/291
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/290
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/289
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/288
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/287
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/286
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/285
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/284
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/283
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/279
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/278
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/277
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/276
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/275
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/273
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/272
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/270
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/269
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/268
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/265
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/264
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/262
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/261
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/259
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/258
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/257
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/256
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/255
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/254
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/253
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/252
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/251
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/250
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/249
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/248
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/246
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/243
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/241
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/275
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/273
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/272
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/270
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/269
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/268
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/265
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/264
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/262
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/261
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/259
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/258
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/257
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/256
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/255
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/254
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/253
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/252
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/251
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/250
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/249
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/248
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/246
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/243
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/241
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/194
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/193
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/192
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/189
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/188
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/186
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/183
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/180
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/179
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/175
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/174
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/173
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/170
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/165
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/163
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/161
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/159
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/157
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/156
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/151
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/148
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/143
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/141
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/138
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/137
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/136
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/135
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/134
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/133
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/132
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/130
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/123
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/119
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/117
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/116
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/115
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/114
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/110
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/109
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/106
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/103
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/101
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/100
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/99
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/96
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/95
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/93
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/92
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/87
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/82
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/74
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/73
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/72
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/70
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/66
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/65
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/64
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/60
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/59
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/54
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/53
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/52
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/51
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/50
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/49
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/48
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/47
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/45
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/44
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/42
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/39
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/38
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/35
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/34
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/29
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/28
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/27
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/26
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/25
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/24
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/23
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/21
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/20
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/18
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/16
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/13
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/12
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/11
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/10


I hope this helps to narrow down the problem,
- Ryan

**Comment by shubhamsharma088** [comment]
The Techs might have been color blind hence the mix up. I'm afraid now you too will have to get color blind filters so both you and your printer can be on same settings.

**Comment by SleepyYui** [comment]
I have another Problem, my Printer now Prints in RGB instead of CMYK

**Comment by 0ttik** [comment]
I'm new Python developer and I can't compile my project, please help! I think it may be connected to this library's printer problem somehow based on my experience I think I'm right.

**Comment by radrow** [comment]
I can confirm the issue

**Comment by brayjamin** [comment]
We're out of paper cups for the water dispenser

**Comment by Tylersuard** [comment]
@brayjamin I could not find a solution for this on StackOverflow.  Have you tried using a debugger?

**Comment by shubhamsharma088** [comment]
I think it’s time to move it on blockchain otherwise we will be stuck with the printer issue forever. It will also allow us to monetise it using smart contract and NFTs.

**Comment by tigercoding56** [comment]
> I think it’s time to move it on blockchain otherwise we will be stuck with the printer issue forever. It will also allow us to monetise it using smart contract and NFTs.

hey we need a roadmap ASAP ,  we need to work on #641 bevore we can commit to  our roadmap though

**Comment by randomfox** [comment]
was a fix found?

**Comment by randomfox** [comment]
Nevermind I fixed mine.

**Comment by radrow** [comment]
I have the same issue

**Comment by stestagg** [comment]
Everyone.  Printer is now AI enabled. 

To print, you have to persuade the AI that you have a valid business case for the use of company resources. 

For color prints, there is a quorum of 5 AIs. You have to persuade a majority before the print request will be accepted. 

Printer output may be edited, paraphrased or summarised to reduce wastage and ensure that all content is compliant with corporate language and phrasing policies. 

For a band 4 exemption, or to delve into the situation further, please email: meredith.palmer.(inactive)@dundermifflin.internal

**Important Reminder** as the AIs represent the future of the company, any abuse or insults directed towards any AI, or any attempt to subvert or ‘jailbreak’ them will result in immediate termination and the replacement of your role with an appropriate AI. 

As a large language model, I am unable to claim that this message was written by a human.  I am also unable to sign off the missive with a witty and motivationally inspiring sign off as this contravenes current corporate AI usage standards.

**Comment by Tylersuard** [comment]
@stestagg I tried to use the printer. I stood at it and I yelled PRINT for half an hour. The printer did not print. How do I activate the AI? I need to print some flyers for my Solstice Beef Party.

**Comment by stestagg** [comment]
@Tylersuard refer to the SOP: DM.AI001.202409

if you’re unable to find the SOP on the intranet. Ask your local friendly AI enabled printer for help locating it (AI printers now also serve as first line IT support and local HR function)

**Comment by radrow** [comment]
@Tylersuard Note that the printer AI follows strict DEI, DYI and ASAP rulesets to provide us with the best possible customer experience. It may or may not, therefore, reject offering you guidance if you do not form your request in a sufficiently inclusive manner. Feel free to use the following prompt-engineered message to increase chances of not getting ghosted by the robot:

```
um53_$LT$impl$u20$core..fmt..LowerHex$u20$for$u20$u32$GT$3fmt17h6e6dfa462c9e0ed6E_ZN4core3fmt3num3imp52_$LT$impl$u20$core..fmt..Display$u20$for$u20$u32$GT$3fmt17he0fe44147a699cc7E_ZN4core3fmt3num53_$LT$impl$u20$core..fmt..UpperHex$u20$for$u20$u32$GT$3fmt17h775efd791f9a8fd9E_ZN4core3fmt3num55_$LT$impl$u20$core..fmt..LowerHex$u20$for$u20$usize$GT$3fmt17hd00902e083423093E_ZN4core3fmt3num3imp54_$LT$impl$u20$core..fmt..Display$u20$for$u20$usize$GT$3fmt17h6eec4baffdfe6412E_ZN4core3fmt3num55_$LT$impl$u20$core..fmt..UpperHex$u20$for$u20$usize$GT$3fmt17h13f7bac3f35106c2Ememset_ZN4core6option15Option$LT$T$GT$4take17h2ad2cbf551c43c1dE_ZN70_$LT$alloc..vec..Vec$LT$T$C$A$GT$$u20$as$u20$core..ops..drop..Drop$GT$4drop17he76f4d9aabbbf5bcE_ZN4core9panicking11panic_const23panic_const_div_by_zero17hcf329dec068cb30eE_ZN4core6result13unwrap_failed17hccc584b9f7c4f4ffE_ZN4core9panicking19assert_failed_inner17hadc13fbfdfc87d4cE_ZN3std3sys3pal4unix17thread_local_dtor13register_dtor17h188feb327f316690E_ZN5alloc3vec12Vec$LT$T$GT$3new17h13c854129733ccb3E_ZN5alloc3vec16Vec$LT$T$C$A$GT$3len17h37d46b5cbc00ec98E_ZN75_$LT$alloc..vec..Vec$LT$T$C$A$GT$$u20$as$u20$core..ops..deref..DerefMut$GT$9deref_mut17h8e7d0c4d0ba33120E_ZN5alloc3vec16Vec$LT$T$C$A$GT$8capacity17hc7845a301bf46febE_ZN4core3cmp3max17had694643ba4e2894E_ZN5alloc3vec16Vec$LT$T$C$A$GT$17try_reserve_exact17hc49d795c37e91884E_ZN4core9panicking11panic_const24panic_const_add_overflow17h417de915343a23abE_ZN5alloc3vec16Vec$LT$T$C$A$GT$4push17h11b71f5394b4e991E_ZN4core9panicking11panic_const24panic_const_sub_overflow17ha63937564c0f48b0Epopejohnpaulthethird2138_ZN4core9panicking5panic17hf61aadc6a500f49eE_ZN72_$LT$alloc..vec..Vec$LT$T$C$A$GT$$u20$as$u20$core..ops..deref..Deref$GT$5deref17h9cd4777b22504ed6E_ZN3std6thread5local17LocalKey$LT$T$GT$8try_with17h9856f58047dc57ebE_ZN12wasm_bindgen9externref23__externref_table_alloc28_$u7b$$u7b$closure$u7d$$u7d$17h46066d166ec57ba1E_ZN3std6thread5local17LocalKey$LT$T$GT$8try_with17h0672b32371d50223E_ZN12wasm_bindgen9externref25__externref_table_dealloc28_$u7b$$u7b$closure$u7d$$u7d$17hc8ee1e7088e093c8E_ZN3std6thread5local17LocalKey$LT$T$GT$8try_with17h66411b816e9bb958E_ZN12wasm_bindgen9externref27__externref_heap_live_count28_$u7b$$u7b$closure$u7d$$u7d$17hce2978a36d043255E__tls_get_addr_ZN4core3ptr13read_volatile18precondition_check17hc58922a21c0f91bfE_ZN5alloc7raw_vec12handle_error17h274dfea84bc10fc8E_ZN4core3cmp6max_by17h67ffd861bb494437E_ZN4core3cmp3Ord3max17h98bff74994d4cd71E_ZN42_$LT$str$u20$as$u20$core..fmt..Display$GT$3fmt17h25a95c537a3254baE_ZN4core3fmt9Formatter9write_str17h808b5c9b4675d8b4E_ZN4core3fmt9Formatter25debug_tuple_field1_finish17h448ddb2d32f0f66fE_ZN3std9panicking12default_hook17h8c8f9c3f5dc8a2fcE_ZN3std9panicking11panic_count18GLOBAL_PANIC_COUNT17hd081a4326368f3c4E_ZN3std9panicking11panic_count17is_zero_slow_path17hf3b98f0d91a091aaE_ZN4core6option13unwrap_failed17h1b4d157238885207E_ZN93_$LT$alloc..collections..btree..mem..replace..PanicGuard$u20$as$u20$core..ops..drop..Drop$GT$4drop17hc152601833cb26afE_ZN4core3fmt8builders10DebugTuple5field17h2338daa84c813e7eE_ZN4core3fmt9Formatter3pad17hbaa59c341d24a08dE_ZN40_$LT$str$u20$as$u20$core..fmt..Debug$GT$3fmt17hd3f4d9ad71a59075E_ZN4core3fmt9Formatter10debug_list17h81a3a9d9f7f80de4E_ZN4core3fmt8builders9DebugList5entry17h086da373413af8a9E_ZN4core3fmt8builders9DebugList6finish17h9df7a02d7ac85664E_ZN60_$LT$core..str..lossy..Debug$u20$as$u20$core..fmt..Debug$GT$3fmt17h3e8bc03bd718b0c3E_ZN4core3fmt3num3imp52_$LT$impl$u20$core..fmt..Display$u20$for$u20$u64$GT$3fmt17hbfbc68b293b68f70E_ZN4core3fmt3num53_$LT$impl$u20$core..fmt..LowerHex$u20$for$u20$u64$GT$3fmt17h3915a38b4e3a4d6dE_ZN4core3fmt3num53_$LT$impl$u20$core..fmt..UpperHex$u
```

**Comment by Pdzly** [comment]
Did you try turning it on and of again?

**Comment by Rakhsan** [comment]
change the ink and try again pls

**Comment by TheoW03** [comment]
have you tried updating the drivers

**Comment by dashmatic** [comment]
Hmmm? Interesting. Works on my machine

**Comment by cootshk** [comment]
I'm having the same issue, pls fix 🙏

**Comment by Rakhsan** [comment]
I fixed it by putting it in oven and goin all out
